name: Democraftic
version: '1.0-SNAPSHOT'
main: org.democraftic.core.Democraftic
api-version: '1.21'
load: STARTUP
authors: [ UnOursPasLa, Eti ]
depend:
  - SimpleClaimSystem
  - ProtocolLib
commands:
  minage:
    description: Téléportation au monde Minage.
  regenMining:
    permission: dc.maintenance.regenworld